### ISSUE TITLE
util/placebo/ - Expired oAuth2 user token

### ISSUE THREAD

**Issue by parallellogic-** [DeviantArt/DeviantArt-API#21] opened 2015-01-05 06:15 UTC
After several hours of usage (paging through the "user/watchers/{username}" endpoint), my app encounters an "Expired oAuth2 user token" error continuously at both the "user/watchers/{username}"  endpoint and the "/util/placebo" endpoints, despite regularly refreshing the access_token.  This app has not yet been published, but I presume that is not significant since the app was previously working.

I access the access_token endpoint for the client through:
https://www.deviantart.com/oauth2/token?grant_type=client_credentials&client_id=xxxx&client_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
I then pass the returned access_token to the placebo endpoint:
https://www.deviantart.com/api/v1/oauth2/placebo?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Instead of the expected "status = success" listed in the documentation, I instead receive an error of "Expired oAuth2 user token. The client should request a new one with an access code or a refresh token", even though my previous endpoint call did just that.  The endpoint is not behaving as expected, so I presume this is a bug.

I have a second app that I have previously published, but not used today.  When I use the above procedure (changing only the client_id and client_secret), I receive the correct "status = success" response from the placebo endpoint.

It is unclear to me if I have hit some sort of undocumented rate limit with the first app or if I have encountered some other bug.

**Comment by KarsonKimbrel** [comment] 2015-01-05 06:18
Duplicate of https://github.com/DeviantArt/DeviantArt-API/issues/2

**Comment by muteor** [comment] 2015-01-05 10:23
Yeah looks like the placebo call is not returning velocity errors correctly, I will get this fixed. Your client was indeed hitting its velocity limit so you will need to slow it down.

**Comment by muteor** [comment] 2015-01-05 15:05
This is fixed and velocity errors should now be returned correctly.

**Closed by muteor** 2015-01-05 15:05 UTC

**Comment by parallellogic-** [comment] 2015-01-05 15:42
It should be noted that rate limits are now only reported for the util/placebo endpoint.  Other endpoints like user/watchers/{username} still return the "Expired oAuth2 user token" error

**Comment by muteor** [comment] 2015-01-05 16:06
Good catch, that should also be fixed too.
